# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mplayer-ruby}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Arthur Chiu"]
  s.date = %q{2010-02-01}
  s.description = %q{A Ruby wrapper for MPlayer}
  s.email = %q{mr.arthur.chiu@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "examples/general_playback.rb",
     "lib/mplayer-ruby.rb",
     "lib/mplayer-ruby/slave.rb",
     "lib/mplayer-ruby/slave_commands.rb",
     "lib/mplayer-ruby/slave_video_commands.rb",
     "test.watchr",
     "test/mplayer-ruby_test.rb",
     "test/slave_commands_test.rb",
     "test/slave_test.rb",
     "test/slave_video_commands_test.rb",
     "test/test.mp3",
     "test/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/achiu/mplayer-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby wrapper for MPlayer}
  s.test_files = [
    "test/mplayer-ruby_test.rb",
     "test/slave_commands_test.rb",
     "test/slave_test.rb",
     "test/slave_video_commands_test.rb",
     "test/teststrap.rb",
     "examples/general_playback.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<riot>, [">= 0.10.11"])
      s.add_development_dependency(%q<rr>, [">= 0.10.5"])
      s.add_runtime_dependency(%q<open4>, [">= 1.0.1"])
    else
      s.add_dependency(%q<riot>, [">= 0.10.11"])
      s.add_dependency(%q<rr>, [">= 0.10.5"])
      s.add_dependency(%q<open4>, [">= 1.0.1"])
    end
  else
    s.add_dependency(%q<riot>, [">= 0.10.11"])
    s.add_dependency(%q<rr>, [">= 0.10.5"])
    s.add_dependency(%q<open4>, [">= 1.0.1"])
  end
end

